/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:d6c611e4-58fe-444f-bcad-822687987187",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_AcXxaO38p",
    "aws_user_pools_web_client_id": "nis7aut18613bu8v6ne6m18p",
    "oauth": {}
};


export default awsmobile;
